name: Report

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull nginx
      - name: Create report for nginx
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx'
          format: 'json'
          output: 'nginx.report.json'
          scanners: 'vuln,secret,config'
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: 'nginx.report.json'
          path: 'ninx.report.json'
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull python
      - name: Create report for python
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python'
          format: 'json'
          output: 'python.report.json'
          scanners: 'vuln,secret,config'
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: 'python.report.json'
          path: 'python.report.json'
        
