name: Report

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  scan-by-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [nginx, python, postgres, node, httpd]
    steps:
      - name: Pull image
        run: docker pull ${{ matrix.image }}
      - name: Create report ${{ matrix.image }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.image }}'
          format: 'json'
          output: '${{ matrix.image }}.report.json'
          scanners: 'vuln,secret,config'
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: '${{ matrix.image }}.report.json'
          path: '${{ matrix.image }}.report.json'
